### ISSUE TITLE
Profile.html

### ISSUE THREAD

**Issue by schwede** [rewilkins/cs2610-group-project#1]
The profile page on some pages is listed as Profile.html and some as profile.html. Can we standardize this so we don't get any broken pages?

**Comment by chapshaun** [comment]
Ok, i changed it to "Profile.html" in my page.
It still worked even though it wasn't capitalized, well let's just be safe.
also, should we make are pages look the same? like schwede has the the same colors but no header, rob has the header but not the same colors.

**Comment by chapshaun** [comment]
These are the colors I used in my css file

body {
  background: #DEDEDE;
}
header {
  background: #2C3539;
  color: #FFF;
}

**Comment by chapshaun** [comment]
Also, is Rob the only one submitting a zip of everything on canvas? or do we all do it?

**Comment by schwede** [comment]
Taken care of...
